apiVersion: v1
kind: Service
metadata:
  name: agent-coredns-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dns-agent-discovery
    app.kubernetes.io/component: coredns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dns-agent-discovery
    app.kubernetes.io/component: coredns
  ports:
    - name: dns-udp
      port: {{ .Values.coredns.service.port }}
      targetPort: dns
      protocol: UDP
      nodePort: {{ .Values.coredns.service.nodePort }}
