apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dns-agent-discovery
    app.kubernetes.io/component: etcd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dns-agent-discovery
    app.kubernetes.io/component: etcd
  ports:
    - name: client
      port: {{ .Values.etcd.service.port }}
      targetPort: client
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dns-agent-discovery
    app.kubernetes.io/component: etcd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dns-agent-discovery
    app.kubernetes.io/component: etcd
  ports:
    - name: client
      port: {{ .Values.etcd.service.port }}
      targetPort: client
      nodePort: {{ .Values.etcd.service.nodePort }}
